### ISSUE TITLE
ScanTailor-Universal crashes when right-clicking a page or trying to inverse page order 

### ISSUE THREAD

**Issue by veikk0** [trufanov-nok/scantailor-universal#78] opened 2021-02-26 23:48 UTC
The program crashes when I right-click any page in the page list or click the "reverse page list" button above the page list.

CLI output:
```
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1416, resource id: 12816231, major code: 40 (TranslateCoords), minor code: 0
Segmentation fault (core dumped)
```
First two lines appear at program start.

Doesn't seem to be related to a specific file, as this happens with any project I try it with, new or old. But I'll attach a test file just in case: [cu31924003574187_0010.jp2.tif.zip](https://github.com/trufanov-nok/scantailor-universal/files/6053210/cu31924003574187_0010.jp2.tif.zip)

* ScanTailor-Universal version: 0.2.10 (installed from `scantailor-universal_0.2.10-0ubuntu1_amd64.deb` downloaded from the releases page here on GitHub)
* OS: Linux Mint 20.1 (based on Ubuntu 20.04)

**Comment by trufanov-nok** [comment] 2021-02-27 01:05
I couldn't reproduce the right-clicking crash, but was able to catch a inverse page order bug. Hope it's the same bug, introduced in 0.2.9. It should be fixed with latest commit in jp2 branch. Could you confirm that the problem is resolved?

**Comment by veikk0** [comment] 2021-02-27 03:02
Thanks, the fix works.

Just as a reference to anyone else trying to build this software (since I found no build instructions), I installed the following packages to build on my Ubuntu 20.04 based distro:

>qttools5-dev qttools5-dev-tools libcanberra-dev libjpeg-dev libtiff-dev libboost-all-dev libopenjp2-7-dev

Then just `mkdir build && cd build && cmake .. && make -j4`. Executable will be in `build/src/app`.

Installing `libboost-all-dev` is probably overkill, but `libboost-dev` wasn't the correct package and there were so many libboost packages that I couldn't be bothered to hunt down the correct one.

**Comment by trufanov-nok** [comment] 2021-02-27 09:01
Hi,
There are a build notes for linux here: https://github.com/trufanov-nok/scantailor-universal/wiki/Building-from-Source-Code-on-Linux-and-Mac-OS-X
I've just updated them.
As for boost: I guess  libboost-dev and libboost-test-dev should be enough.

**Closed by trufanov-nok** 2021-02-27 09:01 UTC
Labels: bug
